/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CesiumFrame: typeof import('./src/components/CesiumFrame.vue')['default']
    Comment: typeof import('./src/components/user/Comment.vue')['default']
    CommentAction: typeof import('./src/components/user/CommentAction.vue')['default']
    CommentFrame: typeof import('./src/components/user/CommentFrame.vue')['default']
    CommentInput: typeof import('./src/components/user/CommentInput.vue')['default']
    CommentLikeButton: typeof import('./src/components/user/CommentLikeButton.vue')['default']
    CommentList: typeof import('./src/components/user/CommentList.vue')['default']
    CommentReplyButton: typeof import('./src/components/user/CommentReplyButton.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    Export: typeof import('./src/components/panels/Export.vue')['default']
    Filter: typeof import('./src/components/panels/Filter.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Layers: typeof import('./src/components/panels/Layers.vue')['default']
    LoginCard: typeof import('./src/components/user/LoginCard.vue')['default']
    NewsChart: typeof import('./src/components/NewsChart.vue')['default']
    Popup: typeof import('./src/components/Popup.vue')['default']
    RegisterCard: typeof import('./src/components/user/RegisterCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/panels/Settings.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SideButton: typeof import('./src/components/SideButton.vue')['default']
  }
}
